node {
  
  stage('GIT CheckOut') {
    git credentialsId: 'MYGIT', url: 'https://github.com/rout-sandeep152/DevOps_Trainning301.git'
  }

  def project_path = "02-Jenkins/Code/petclinic"
  
  dir(project_path) {

  stage('Maven-Clean') {
    sh label: '', script: 'mvn clean'
  }

  stage('Maven-Compile') {
    sh label: '', script: 'mvn compile'
  }
  
  stage('Maven-Test') {
    sh label: '', script: 'mvn test'
  }
  
  stage('Maven-Package') {
    sh label: '', script: 'mvn package'
  }

  stage('Stage Deployment- Env Docker') {
    sh label: '', script: 'sudo docker-compose up -d --build'
  }
 }
}
